-- DropForeignKey
ALTER TABLE "GHE_SUATCHIEU" DROP CONSTRAINT "GHE_SUATCHIEU_maSuatChieu_fkey";

-- AddForeignKey
ALTER TABLE "GHE_SUATCHIEU" ADD CONSTRAINT "GHE_SUATCHIEU_maSuatChieu_fkey" FOREIGN KEY ("maSuatChieu") REFERENCES "SUATCHIEU"("maSuatChieu") ON DELETE CASCADE ON UPDATE CASCADE;
