-- DropForeignKey
ALTER TABLE "NGUOIDUNG" DROP CONSTRAINT "NGUOIDUNG_maLoaiNguoiDung_fkey";

-- DropForeignKey
ALTER TABLE "PHIM" DROP CONSTRAINT "PHIM_maPhanLoaiDoTuoi_fkey";

-- DropForeignKey
ALTER TABLE "PHIM_THELOAI" DROP CONSTRAINT "PHIM_THELOAI_maPhim_fkey";

-- DropForeignKey
ALTER TABLE "PHIM_THELOAI" DROP CONSTRAINT "PHIM_THELOAI_maTheLoai_fkey";

-- AddForeignKey
ALTER TABLE "NGUOIDUNG" ADD CONSTRAINT "NGUOIDUNG_maLoaiNguoiDung_fkey" FOREIGN KEY ("maLoaiNguoiDung") REFERENCES "LOAINGUOIDUNG"("maLoaiNguoiDung") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHIM_THELOAI" ADD CONSTRAINT "PHIM_THELOAI_maPhim_fkey" FOREIGN KEY ("maPhim") REFERENCES "PHIM"("maPhim") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHIM_THELOAI" ADD CONSTRAINT "PHIM_THELOAI_maTheLoai_fkey" FOREIGN KEY ("maTheLoai") REFERENCES "THELOAI"("maTheLoai") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHIM" ADD CONSTRAINT "PHIM_maPhanLoaiDoTuoi_fkey" FOREIGN KEY ("maPhanLoaiDoTuoi") REFERENCES "PHANLOAIDOTUOI"("maPhanLoaiDoTuoi") ON DELETE CASCADE ON UPDATE CASCADE;
