-- AlterTable
ALTER TABLE "HOADON_COMBO" ADD COLUMN     "maNhanVienSoatBapNuoc" TEXT;

-- AlterTable
ALTER TABLE "HOADON_SANPHAM" ADD COLUMN     "maNhanVienSoatBapNuoc" TEXT;

-- AlterTable
ALTER TABLE "VE" ADD COLUMN     "maNhanVienSoatVe" TEXT;

-- AddForeignKey
ALTER TABLE "VE" ADD CONSTRAINT "VE_maNhanVienSoatVe_fkey" FOREIGN KEY ("maNhanVienSoatVe") REFERENCES "NGUOIDUNG"("maNguoiDung") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HOADON_COMBO" ADD CONSTRAINT "HOADON_COMBO_maNhanVienSoatBapNuoc_fkey" FOREIGN KEY ("maNhanVienSoatBapNuoc") REFERENCES "NGUOIDUNG"("maNguoiDung") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HOADON_SANPHAM" ADD CONSTRAINT "HOADON_SANPHAM_maNhanVienSoatBapNuoc_fkey" FOREIGN KEY ("maNhanVienSoatBapNuoc") REFERENCES "NGUOIDUNG"("maNguoiDung") ON DELETE SET NULL ON UPDATE CASCADE;
