-- DropForeignKey
ALTER TABLE "CHITIETCOMBO" DROP CONSTRAINT "CHITIETCOMBO_maCombo_fkey";

-- DropForeignKey
ALTER TABLE "CHITIETCOMBO" DROP CONSTRAINT "CHITIETCOMBO_maSanPham_fkey";

-- DropForeignKey
ALTER TABLE "CHITIETVE" DROP CONSTRAINT "CHITIETVE_maGhe_fkey";

-- DropForeignKey
ALTER TABLE "CHITIETVE" DROP CONSTRAINT "CHITIETVE_maVe_fkey";

-- DropForeignKey
ALTER TABLE "GHE_SUATCHIEU" DROP CONSTRAINT "GHE_SUATCHIEU_maGhe_fkey";

-- DropForeignKey
ALTER TABLE "GHE_SUATCHIEU" DROP CONSTRAINT "GHE_SUATCHIEU_maSuatChieu_fkey";

-- DropForeignKey
ALTER TABLE "PHIM_THELOAI" DROP CONSTRAINT "PHIM_THELOAI_maPhim_fkey";

-- DropForeignKey
ALTER TABLE "PHIM_THELOAI" DROP CONSTRAINT "PHIM_THELOAI_maTheLoai_fkey";

-- DropForeignKey
ALTER TABLE "VE_COMBO" DROP CONSTRAINT "VE_COMBO_maCombo_fkey";

-- DropForeignKey
ALTER TABLE "VE_COMBO" DROP CONSTRAINT "VE_COMBO_maVe_fkey";

-- DropForeignKey
ALTER TABLE "VE_SANPHAM" DROP CONSTRAINT "VE_SANPHAM_maSanPham_fkey";

-- DropForeignKey
ALTER TABLE "VE_SANPHAM" DROP CONSTRAINT "VE_SANPHAM_maVe_fkey";

-- AddForeignKey
ALTER TABLE "PHIM_THELOAI" ADD CONSTRAINT "PHIM_THELOAI_maPhim_fkey" FOREIGN KEY ("maPhim") REFERENCES "PHIM"("maPhim") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHIM_THELOAI" ADD CONSTRAINT "PHIM_THELOAI_maTheLoai_fkey" FOREIGN KEY ("maTheLoai") REFERENCES "THELOAI"("maTheLoai") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GHE_SUATCHIEU" ADD CONSTRAINT "GHE_SUATCHIEU_maGhe_fkey" FOREIGN KEY ("maGhe") REFERENCES "GHE"("maGhe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GHE_SUATCHIEU" ADD CONSTRAINT "GHE_SUATCHIEU_maSuatChieu_fkey" FOREIGN KEY ("maSuatChieu") REFERENCES "SUATCHIEU"("maSuatChieu") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHITIETCOMBO" ADD CONSTRAINT "CHITIETCOMBO_maCombo_fkey" FOREIGN KEY ("maCombo") REFERENCES "COMBO"("maCombo") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHITIETCOMBO" ADD CONSTRAINT "CHITIETCOMBO_maSanPham_fkey" FOREIGN KEY ("maSanPham") REFERENCES "SANPHAM"("maSanPham") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHITIETVE" ADD CONSTRAINT "CHITIETVE_maVe_fkey" FOREIGN KEY ("maVe") REFERENCES "VE"("maVe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHITIETVE" ADD CONSTRAINT "CHITIETVE_maGhe_fkey" FOREIGN KEY ("maGhe") REFERENCES "GHE"("maGhe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_COMBO" ADD CONSTRAINT "VE_COMBO_maVe_fkey" FOREIGN KEY ("maVe") REFERENCES "VE"("maVe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_COMBO" ADD CONSTRAINT "VE_COMBO_maCombo_fkey" FOREIGN KEY ("maCombo") REFERENCES "COMBO"("maCombo") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_SANPHAM" ADD CONSTRAINT "VE_SANPHAM_maVe_fkey" FOREIGN KEY ("maVe") REFERENCES "VE"("maVe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_SANPHAM" ADD CONSTRAINT "VE_SANPHAM_maSanPham_fkey" FOREIGN KEY ("maSanPham") REFERENCES "SANPHAM"("maSanPham") ON DELETE CASCADE ON UPDATE CASCADE;
