-- DropForeignKey
ALTER TABLE "CHITIETCOMBO" DROP CONSTRAINT "CHITIETCOMBO_maCombo_fkey";

-- DropForeignKey
ALTER TABLE "CHITIETCOMBO" DROP CONSTRAINT "CHITIETCOMBO_maSanPham_fkey";

-- DropForeignKey
ALTER TABLE "CHITIETVE" DROP CONSTRAINT "CHITIETVE_maGhe_fkey";

-- DropForeignKey
ALTER TABLE "CHITIETVE" DROP CONSTRAINT "CHITIETVE_maVe_fkey";

-- DropForeignKey
ALTER TABLE "DIEUKIENKHUYENMAI" DROP CONSTRAINT "DIEUKIENKHUYENMAI_maLoaiNguoiDung_fkey";

-- DropForeignKey
ALTER TABLE "GHE" DROP CONSTRAINT "GHE_maLoaiGhe_fkey";

-- DropForeignKey
ALTER TABLE "GHE" DROP CONSTRAINT "GHE_maPhong_fkey";

-- DropForeignKey
ALTER TABLE "GHE_SUATCHIEU" DROP CONSTRAINT "GHE_SUATCHIEU_maGhe_fkey";

-- DropForeignKey
ALTER TABLE "GHE_SUATCHIEU" DROP CONSTRAINT "GHE_SUATCHIEU_maSuatChieu_fkey";

-- DropForeignKey
ALTER TABLE "GIAGHEPHONG" DROP CONSTRAINT "GIAGHEPHONG_maLoaiGhe_fkey";

-- DropForeignKey
ALTER TABLE "GIAGHEPHONG" DROP CONSTRAINT "GIAGHEPHONG_maLoaiPhong_fkey";

-- DropForeignKey
ALTER TABLE "KHUYENMAI" DROP CONSTRAINT "KHUYENMAI_maDieuKien_fkey";

-- DropForeignKey
ALTER TABLE "NGUOIDUNG" DROP CONSTRAINT "NGUOIDUNG_maLoaiNguoiDung_fkey";

-- DropForeignKey
ALTER TABLE "PHIM" DROP CONSTRAINT "PHIM_maPhanLoaiDoTuoi_fkey";

-- DropForeignKey
ALTER TABLE "PHIM_THELOAI" DROP CONSTRAINT "PHIM_THELOAI_maPhim_fkey";

-- DropForeignKey
ALTER TABLE "PHIM_THELOAI" DROP CONSTRAINT "PHIM_THELOAI_maTheLoai_fkey";

-- DropForeignKey
ALTER TABLE "PHONGCHIEU" DROP CONSTRAINT "PHONGCHIEU_maLoaiPhong_fkey";

-- DropForeignKey
ALTER TABLE "PHONGCHIEU" DROP CONSTRAINT "PHONGCHIEU_maRap_fkey";

-- DropForeignKey
ALTER TABLE "SANPHAM" DROP CONSTRAINT "SANPHAM_maDanhMucSanPham_fkey";

-- DropForeignKey
ALTER TABLE "SUATCHIEU" DROP CONSTRAINT "SUATCHIEU_maPhim_fkey";

-- DropForeignKey
ALTER TABLE "SUATCHIEU" DROP CONSTRAINT "SUATCHIEU_maPhong_fkey";

-- DropForeignKey
ALTER TABLE "VE" DROP CONSTRAINT "VE_maPhim_fkey";

-- DropForeignKey
ALTER TABLE "VE" DROP CONSTRAINT "VE_maSuatChieu_fkey";

-- DropForeignKey
ALTER TABLE "VE_COMBO" DROP CONSTRAINT "VE_COMBO_maCombo_fkey";

-- DropForeignKey
ALTER TABLE "VE_COMBO" DROP CONSTRAINT "VE_COMBO_maVe_fkey";

-- DropForeignKey
ALTER TABLE "VE_SANPHAM" DROP CONSTRAINT "VE_SANPHAM_maSanPham_fkey";

-- DropForeignKey
ALTER TABLE "VE_SANPHAM" DROP CONSTRAINT "VE_SANPHAM_maVe_fkey";

-- AddForeignKey
ALTER TABLE "NGUOIDUNG" ADD CONSTRAINT "NGUOIDUNG_maLoaiNguoiDung_fkey" FOREIGN KEY ("maLoaiNguoiDung") REFERENCES "LOAINGUOIDUNG"("maLoaiNguoiDung") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHIM_THELOAI" ADD CONSTRAINT "PHIM_THELOAI_maPhim_fkey" FOREIGN KEY ("maPhim") REFERENCES "PHIM"("maPhim") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHIM_THELOAI" ADD CONSTRAINT "PHIM_THELOAI_maTheLoai_fkey" FOREIGN KEY ("maTheLoai") REFERENCES "THELOAI"("maTheLoai") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHIM" ADD CONSTRAINT "PHIM_maPhanLoaiDoTuoi_fkey" FOREIGN KEY ("maPhanLoaiDoTuoi") REFERENCES "PHANLOAIDOTUOI"("maPhanLoaiDoTuoi") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHONGCHIEU" ADD CONSTRAINT "PHONGCHIEU_maLoaiPhong_fkey" FOREIGN KEY ("maLoaiPhong") REFERENCES "LOAIPHONGCHIEU"("maLoaiPhong") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHONGCHIEU" ADD CONSTRAINT "PHONGCHIEU_maRap_fkey" FOREIGN KEY ("maRap") REFERENCES "RAP"("maRap") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUATCHIEU" ADD CONSTRAINT "SUATCHIEU_maPhim_fkey" FOREIGN KEY ("maPhim") REFERENCES "PHIM"("maPhim") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUATCHIEU" ADD CONSTRAINT "SUATCHIEU_maPhong_fkey" FOREIGN KEY ("maPhong") REFERENCES "PHONGCHIEU"("maPhong") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GIAGHEPHONG" ADD CONSTRAINT "GIAGHEPHONG_maLoaiGhe_fkey" FOREIGN KEY ("maLoaiGhe") REFERENCES "LOAIGHE"("maLoaiGhe") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GIAGHEPHONG" ADD CONSTRAINT "GIAGHEPHONG_maLoaiPhong_fkey" FOREIGN KEY ("maLoaiPhong") REFERENCES "LOAIPHONGCHIEU"("maLoaiPhong") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GHE" ADD CONSTRAINT "GHE_maLoaiGhe_fkey" FOREIGN KEY ("maLoaiGhe") REFERENCES "LOAIGHE"("maLoaiGhe") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GHE" ADD CONSTRAINT "GHE_maPhong_fkey" FOREIGN KEY ("maPhong") REFERENCES "PHONGCHIEU"("maPhong") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GHE_SUATCHIEU" ADD CONSTRAINT "GHE_SUATCHIEU_maGhe_fkey" FOREIGN KEY ("maGhe") REFERENCES "GHE"("maGhe") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GHE_SUATCHIEU" ADD CONSTRAINT "GHE_SUATCHIEU_maSuatChieu_fkey" FOREIGN KEY ("maSuatChieu") REFERENCES "SUATCHIEU"("maSuatChieu") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SANPHAM" ADD CONSTRAINT "SANPHAM_maDanhMucSanPham_fkey" FOREIGN KEY ("maDanhMucSanPham") REFERENCES "DANHMUCSANPHAM"("maDanhMucSanPham") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHITIETCOMBO" ADD CONSTRAINT "CHITIETCOMBO_maCombo_fkey" FOREIGN KEY ("maCombo") REFERENCES "COMBO"("maCombo") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHITIETCOMBO" ADD CONSTRAINT "CHITIETCOMBO_maSanPham_fkey" FOREIGN KEY ("maSanPham") REFERENCES "SANPHAM"("maSanPham") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DIEUKIENKHUYENMAI" ADD CONSTRAINT "DIEUKIENKHUYENMAI_maLoaiNguoiDung_fkey" FOREIGN KEY ("maLoaiNguoiDung") REFERENCES "LOAINGUOIDUNG"("maLoaiNguoiDung") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "KHUYENMAI" ADD CONSTRAINT "KHUYENMAI_maDieuKien_fkey" FOREIGN KEY ("maDieuKien") REFERENCES "DIEUKIENKHUYENMAI"("maDieuKien") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE" ADD CONSTRAINT "VE_maPhim_fkey" FOREIGN KEY ("maPhim") REFERENCES "PHIM"("maPhim") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE" ADD CONSTRAINT "VE_maSuatChieu_fkey" FOREIGN KEY ("maSuatChieu") REFERENCES "SUATCHIEU"("maSuatChieu") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHITIETVE" ADD CONSTRAINT "CHITIETVE_maVe_fkey" FOREIGN KEY ("maVe") REFERENCES "VE"("maVe") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHITIETVE" ADD CONSTRAINT "CHITIETVE_maGhe_fkey" FOREIGN KEY ("maGhe") REFERENCES "GHE"("maGhe") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_COMBO" ADD CONSTRAINT "VE_COMBO_maVe_fkey" FOREIGN KEY ("maVe") REFERENCES "VE"("maVe") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_COMBO" ADD CONSTRAINT "VE_COMBO_maCombo_fkey" FOREIGN KEY ("maCombo") REFERENCES "COMBO"("maCombo") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_SANPHAM" ADD CONSTRAINT "VE_SANPHAM_maVe_fkey" FOREIGN KEY ("maVe") REFERENCES "VE"("maVe") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_SANPHAM" ADD CONSTRAINT "VE_SANPHAM_maSanPham_fkey" FOREIGN KEY ("maSanPham") REFERENCES "SANPHAM"("maSanPham") ON DELETE RESTRICT ON UPDATE CASCADE;
