-- CreateEnum
CREATE TYPE "TRANGTHAIGHE" AS ENUM ('DangTrong', 'KhongSuDung', 'DangDuocChon', 'DaDat');

-- CreateTable
CREATE TABLE "GIAGHEPHONG" (
    "maLoaiPhong" TEXT NOT NULL,
    "maLoaiGhe" TEXT NOT NULL,
    "giaTien" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "GIAGHEPHONG_pkey" PRIMARY KEY ("maLoaiPhong","maLoaiGhe")
);

-- CreateTable
CREATE TABLE "LOAIGHE" (
    "maLoaiGhe" TEXT NOT NULL,
    "tenLoaiGhe" TEXT NOT NULL,
    "moTa" TEXT,

    CONSTRAINT "LOAIGHE_pkey" PRIMARY KEY ("maLoaiGhe")
);

-- CreateTable
CREATE TABLE "GHE" (
    "maGhe" TEXT NOT NULL,
    "maPhong" TEXT NOT NULL,
    "hangGhe" TEXT NOT NULL,
    "soGhe" INTEGER NOT NULL,
    "maLoaiGhe" TEXT NOT NULL,

    CONSTRAINT "GHE_pkey" PRIMARY KEY ("maGhe")
);

-- CreateTable
CREATE TABLE "GHE_SUATCHIEU" (
    "maGhe" TEXT NOT NULL,
    "maSuatChieu" TEXT NOT NULL,
    "trangThaiGhe" "TRANGTHAIGHE" NOT NULL DEFAULT 'DangTrong',

    CONSTRAINT "GHE_SUATCHIEU_pkey" PRIMARY KEY ("maGhe","maSuatChieu")
);

-- AddForeignKey
ALTER TABLE "GIAGHEPHONG" ADD CONSTRAINT "GIAGHEPHONG_maLoaiGhe_fkey" FOREIGN KEY ("maLoaiGhe") REFERENCES "LOAIGHE"("maLoaiGhe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GIAGHEPHONG" ADD CONSTRAINT "GIAGHEPHONG_maLoaiPhong_fkey" FOREIGN KEY ("maLoaiPhong") REFERENCES "LOAIPHONGCHIEU"("maLoaiPhong") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GHE" ADD CONSTRAINT "GHE_maLoaiGhe_fkey" FOREIGN KEY ("maLoaiGhe") REFERENCES "LOAIGHE"("maLoaiGhe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GHE" ADD CONSTRAINT "GHE_maPhong_fkey" FOREIGN KEY ("maPhong") REFERENCES "PHONGCHIEU"("maPhong") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GHE_SUATCHIEU" ADD CONSTRAINT "GHE_SUATCHIEU_maGhe_fkey" FOREIGN KEY ("maGhe") REFERENCES "GHE"("maGhe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GHE_SUATCHIEU" ADD CONSTRAINT "GHE_SUATCHIEU_maSuatChieu_fkey" FOREIGN KEY ("maSuatChieu") REFERENCES "SUATCHIEU"("maSuatChieu") ON DELETE CASCADE ON UPDATE CASCADE;
