-- CreateTable
CREATE TABLE "SUATCHIEU" (
    "maSuatChieu" TEXT NOT NULL,
    "maPhim" TEXT NOT NULL,
    "maPhong" TEXT NOT NULL,
    "ngayChieu" DATE NOT NULL,
    "gioChieu" TIME NOT NULL,
    "gioKetThuc" TIME NOT NULL,

    CONSTRAINT "SUATCHIEU_pkey" PRIMARY KEY ("maSuatChieu")
);

-- AddForeignKey
ALTER TABLE "SUATCHIEU" ADD CONSTRAINT "SUATCHIEU_maPhim_fkey" FOREIGN KEY ("maPhim") REFERENCES "PHIM"("maPhim") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUATCHIEU" ADD CONSTRAINT "SUATCHIEU_maPhong_fkey" FOREIGN KEY ("maPhong") REFERENCES "PHONGCHIEU"("maPhong") ON DELETE CASCADE ON UPDATE CASCADE;
