-- CreateTable
CREATE TABLE "VE" (
    "maVe" TEXT NOT NULL,
    "maSuatChieu" TEXT NOT NULL,
    "maNguoiDung" TEXT NOT NULL,
    "maNhanVienDat" TEXT,
    "maQR" TEXT NOT NULL,
    "hinhThuc" TEXT NOT NULL,
    "maGiaoDich" TEXT,
    "ngayMua" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tongTien" DOUBLE PRECISION NOT NULL,
    "daCheckIn" BOOLEAN NOT NULL DEFAULT false,
    "thoiGianCheckIn" TIMESTAMP(3),
    "maNhanVienSoat" TEXT,
    "maKhuyenMai" TEXT,
    "ngayHoanTien" TIMESTAMP(3),
    "noiDungHoan" TEXT,

    CONSTRAINT "VE_pkey" PRIMARY KEY ("maVe")
);

-- CreateTable
CREATE TABLE "CHITIETVE" (
    "maVe" TEXT NOT NULL,
    "maGhe" TEXT NOT NULL,
    "donGia" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "CHITIETVE_pkey" PRIMARY KEY ("maVe","maGhe")
);

-- CreateTable
CREATE TABLE "VE_COMBO" (
    "maVe" TEXT NOT NULL,
    "maCombo" TEXT NOT NULL,
    "soLuong" INTEGER NOT NULL,
    "donGia" DOUBLE PRECISION NOT NULL,
    "tongTien" DOUBLE PRECISION NOT NULL,
    "daLay" BOOLEAN NOT NULL DEFAULT false,
    "thoiGianLay" TIMESTAMP(3),

    CONSTRAINT "VE_COMBO_pkey" PRIMARY KEY ("maVe","maCombo")
);

-- CreateTable
CREATE TABLE "VE_SANPHAM" (
    "maVe" TEXT NOT NULL,
    "maSanPham" TEXT NOT NULL,
    "soLuong" INTEGER NOT NULL,
    "donGia" DOUBLE PRECISION NOT NULL,
    "tongTien" DOUBLE PRECISION NOT NULL,
    "daLay" BOOLEAN NOT NULL DEFAULT false,
    "thoiGianLay" TIMESTAMP(3),

    CONSTRAINT "VE_SANPHAM_pkey" PRIMARY KEY ("maVe","maSanPham")
);

-- CreateIndex
CREATE UNIQUE INDEX "VE_maQR_key" ON "VE"("maQR");

-- AddForeignKey
ALTER TABLE "VE" ADD CONSTRAINT "VE_maNguoiDung_fkey" FOREIGN KEY ("maNguoiDung") REFERENCES "NGUOIDUNG"("maNguoiDung") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE" ADD CONSTRAINT "VE_maNhanVienDat_fkey" FOREIGN KEY ("maNhanVienDat") REFERENCES "NGUOIDUNG"("maNguoiDung") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE" ADD CONSTRAINT "VE_maNhanVienSoat_fkey" FOREIGN KEY ("maNhanVienSoat") REFERENCES "NGUOIDUNG"("maNguoiDung") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE" ADD CONSTRAINT "VE_maSuatChieu_fkey" FOREIGN KEY ("maSuatChieu") REFERENCES "SUATCHIEU"("maSuatChieu") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHITIETVE" ADD CONSTRAINT "CHITIETVE_maVe_fkey" FOREIGN KEY ("maVe") REFERENCES "VE"("maVe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHITIETVE" ADD CONSTRAINT "CHITIETVE_maGhe_fkey" FOREIGN KEY ("maGhe") REFERENCES "GHE"("maGhe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_COMBO" ADD CONSTRAINT "VE_COMBO_maVe_fkey" FOREIGN KEY ("maVe") REFERENCES "VE"("maVe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_COMBO" ADD CONSTRAINT "VE_COMBO_maCombo_fkey" FOREIGN KEY ("maCombo") REFERENCES "COMBO"("maCombo") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_SANPHAM" ADD CONSTRAINT "VE_SANPHAM_maVe_fkey" FOREIGN KEY ("maVe") REFERENCES "VE"("maVe") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VE_SANPHAM" ADD CONSTRAINT "VE_SANPHAM_maSanPham_fkey" FOREIGN KEY ("maSanPham") REFERENCES "SANPHAM"("maSanPham") ON DELETE CASCADE ON UPDATE CASCADE;
